spring:
  datasource:
    url: jdbc:mysql://192.168.1.104:3306/elevators?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    username: remoteuser
    password: remoteuser1@
#    url: jdbc:mysql://www.zjtb.xyz:3306/elevators?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
#    username: root
#    password: 008e9ed3ec92
    driver-class-name: com.mysql.jdbc.Driver
#  mvc:
#    view:
#      suffix: .html
#      prefix: /
server:
  port: 8999
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false